### ISSUE TITLE
Arguments to `grts()`

### ISSUE THREAD

**Issue by steffilazerte** [dhope/BASSr#4]
Regarding which arguments to hardcode, set as defaults, or pass via ... to `spsurvey::grts()`. 
- Related to [#2 in this PR Comment](https://github.com/dhope/BASSr/pull/2#issuecomment-1635906025)
- Applies to `draw_random_samples()`, `run_grts_on_BASS()`

**`mindis` and `maxtry`**
We can definitely can pass `mindis` and `maxtry` because the defaults in `grst()` are the same used by `BASSr` and it makes sense to allow the user to change these.

**`DesignID` and `aux_var`**
However, I'm not sure I'd pass  `DesignID` or `aux_var` (only applies to `run_grts_on_BASS()` as ... and further, I don't think I'd allow the user to change them either. 
- First, because the default values in `grts()` are `Site` and `NULL` respectively, whereas `run_grts_on_BASS` currently passes `sample` and `inclpr`, so the user would *have* to supply these values as the default `grts()` values wouldn't be the same for `DesignID` and would be outright incorrect for `aux_var`  (which should usually be "inclpr")
- Second, because BASSr is designed to do a specific type of sampling. I'm not sure it makes sense to allow the user to sample based on something other than `inclpr`. If they want to, it might be best if they do it completely separate from BASSr functions. While the `siteID` value created by using `DesignID = "sample"` isn't really used internally in BASSr it's also not really an important thing to change.

I'd suggest 
- Pass `mindis` and `maxtry` as arguments through ...
- Pass `DesignID` as an argument through ... (which means that the `SiteID` column would now contain `Site-1` rather than `sample-1`) **OR** hardcode `DesignID = "`sample`" (no change)
- Hardcode `aux_var = "inclpr"` (no change) **OR** add `aux_var = "inclpr"` as an argument to the BASSr functions so the default is at least set

Thoughts?

**Comment by dhope** [comment]
Oops sorry @steffilazerte. I did the code review before getting to this. I think the "Site" vs "Sample" will make do difference to the user, so can go ahead and tuck that into the `...`. 

After reading your thinking I do tend to agree with your logic that this is a specific use of `GRTS`, so if they want to do something too different they should just call `grts` directly. My only thought for another use case would be if someone wanted to select on benefits directly without costs (though I believe the code handles that directly now doesn't it). Also, I have the internal functions calculating PPS and z-scores. To allow for flexibility, I'd suggest adding the `aux_var` variable directly, but call it something more readable like `selection_weighting`.  

Thanks and again no rush on this.

**Comment by steffilazerte** [comment]
Sounds good, I'll make those changes!
