### ISSUE TITLE
Function - genSSU()

### ISSUE THREAD

**Issue by steffilazerte** [dhope/BASSr#6]
This is a placeholder issue for discussions regarding `genSSU()`.

**Comment by steffilazerte** [comment]
@dhope a couple of questions
1. Is there any reason we *shouldn't* have this function create SSUs for multiple hexagons? That way if you give it a single hexagon, you get the original behaviour, but you could also give it a sf data frame with multiple hexes instead of having to `map()` over it yourself.
2. What about renaming these three functions (`create_study_area()`, `genSSU()`, `select_ssu()`) to better reflect their relationship with each other?
    - If PSU and SSU are standard terms or specific technical ones you want to emphasize here, how about
       **`create_psu()` -> `create_ssu()` -> `select_ssu()`**?
    - Otherwise, if PSU/SSU are a bit esoteric, and you want to emphasize more general terms, how about 
      **`create_area()` -> `create_sites()` -> `select_sites()`?**

**Comment by dhope** [comment]
I think for 1, no I can't see a reason to limit functionality to just external `map()` usage. I suspect these were not used enough for me to modify the function to allow this. It is a good idea!

For 2. I took a look at the functions you've already worked on and probably the most consistent is:
`create_hexagons()` (or `create_hex()`?) -> `create_sites()` -> `select_sites()`
We don't use SSUs or PSUs in any other functions I don' think and area and sites are less jargony, so agree that is better than psu/ssu.

**Comment by steffilazerte** [comment]
Good idea! What about  `create_hexes()`? Or am I getting pedantic?

**Comment by dhope** [comment]
Sounds good. `create_hex()` might send the wrong message. 🧙‍♀️

**Comment by steffilazerte** [comment]
Hah, but hexes is just multiple 🧙🏼 🧙🏼‍♂️ 🧙🏼‍♀️ 🪄 😈

**Comment by steffilazerte** [comment]
Okay, I think this one is good to go, there's an option to create sites by number as well, and it iterates over hex ids.

**Comment by dhope** [comment]
Looks good. I'm going to close this now.
