### ISSUE TITLE
Function - select_ssu()

### ISSUE THREAD

**Issue by steffilazerte** [dhope/BASSr#7]
This is a placeholder issue for discussions regarding `select_ssu()`.

**Comment by steffilazerte** [comment]
Hi David, 
I'm starting on this one and had a question about the random sampling option. Here you have options to run Clusters and Random sampling with or without GRTS. Is that still the functionality you would like? Or should they always be run with GRTS? Just checking because I thought we removed non-GRTS options in other places (but I might be mis-remembering).

**Comment by steffilazerte** [comment]
@dhope do you have an example with outputs for the shortest path in select_ssu / select_sites? I'm struggling a bit to understand how this part of the function works and it would help if I had an expected output to compare. Thanks!

**Comment by steffilazerte** [comment]
@dhope Ooookay, more questions, but I think I'm getting there for the clusters and the random sampling.

I am starting to get close to the end of my hours, so am trying to be efficient with this as I still have to go back to finish up the ARUtools stuff 😬 

### For clusters
- Although there is a warning about min_dist < 900 because of potential overlap among clusters, doesn't it really depend on a) How close the sites are, and b) The number of sites to be sampled? Would it be better to warn the user if there is overlap, rather than have a generic size warning?
- The within cluster distance of `600` metres is hard-coded, would that be better as an argument that could be adjusted?
- What is `PC` vs. `ARU` in the `ARU` column of the clusters (and the Rabdom sites, where they're all `PC`).

### In general
- Should the sampling be stratified by hex?
 

### In general, do these samplings look appropriate?
These plots show a hex grid (`create_hexes()`), with sites (`create_sites()`) on the selected hexes (`run_grts_on_BASS()`), and then the selected sites (`select_sites()`)

**Clustered samples** 
- 100 samples, 20 cluster size (min dist 30 and within cluster dist 10)
![image](https://github.com/dhope/BASSr/assets/14676081/6eb3cb23-789d-49cb-a84f-eb9caf5a741a)

**Random samples**
- 18 samples, 
![image](https://github.com/dhope/BASSr/assets/14676081/119648d0-0406-4309-a1f2-f9860bea9248)

**Comment by dhope** [comment]
> Hi David, I'm starting on this one and had a question about the random sampling option. Here you have options to run Clusters and Random sampling with or without GRTS. Is that still the functionality you would like? Or should they always be run with GRTS? Just checking because I thought we removed non-GRTS options in other places (but I might be mis-remembering).

Yeah we want the non-grts option for the sites, just because GRTS is less relevant for small plots, and can be fairly resource heavy to run.

**Comment by dhope** [comment]
> @dhope do you have an example with outputs for the shortest path in select_ssu / select_sites? I'm struggling a bit to understand how this part of the function works and it would help if I had an expected output to compare. Thanks!

Yup, will send via email.

**Comment by steffilazerte** [comment]
Great thanks for your speedy response!

**Comment by steffilazerte** [comment]
Okay, I think I've got the standard Clusters and Random with GRTS sorted out and am pretty close with the shortest paths.
I've fixed the sampling for GRTS to work per hex, and I'm really excited that I was able to make the shortest path sampling programmatic to how ever many clusters you want 🎉 . I do still have questions about hard-coded values in Paths and unexpected behaviour with non-GRTS sampling, where I'm not sure if it should remain that way, or, if not, what the alternative should be.

### Visual update
*Click on an image enlarge*

<img src = "https://github.com/dhope/BASSr/assets/14676081/d729b396-2b7c-4c6a-8c50-6d7c98b67795" width = "33%">
<img src = "https://github.com/dhope/BASSr/assets/14676081/946ee0e7-81ef-4e96-a972-be0e31b357c3" width = "33%">
<img src = "https://github.com/dhope/BASSr/assets/14676081/0d11901e-b2ee-482e-bb63-9ad272c914b6" width = "33%">

### But still some questions...

**Shortest path**
In the examples I have, the spacing among sites is 300m, but the `min_dist` used in the functions is also 300m. So I have a couple of questions about how to replace the hard-coded options with more flexible variables

- The [buffer distance](https://github.com/dhope/BASSr/blob/e4b02da4410d0f1887edc4413eb6fd8023e85202/R/SSU_selection_methods.R#L197-L198) around the sites is `20 + sqrt(2 * (300**2))`. 
    - To allow this to be flexible, should this be `20 + sqrt(2 * (spacing**2))`? Or should I use `min_dist`?
- The [weighted distance between points](https://github.com/dhope/BASSr/blob/e4b02da4410d0f1887edc4413eb6fd8023e85202/R/SSU_selection_methods.R#L208) in a path is hard-coded as 150 being too close, min_dist + 5 good, and everything else intermediate (if I've understood). 
    - Should 150 be replace with `spacing/2` ?


**Non-GRTS Sampling**

- The functions use (or create) the `scaled_benefit` column, but [sometimes use the `benefit` column to sort the data](https://github.com/dhope/BASSr/blob/e4b02da4410d0f1887edc4413eb6fd8023e85202/R/SSU_selection_methods.R#L45)... is this as expected, or should they be sorting by `scaled_benefit`?
- Non-GRTS doesn't seem to use `min_dist`, so there is no check for the distance between sampled sites... is this as expected?
- Non-GRTS Clusters only accept samples if at least two points are with 675m of each other [ie. the minimum distance among points is < 675m](https://github.com/dhope/BASSr/blob/e4b02da4410d0f1887edc4413eb6fd8023e85202/R/SSU_selection_methods.R#L38-L50), is this as expected?

**Random Sampling**
- For ARUonly, all points are labelled "ARU" if TRUE and "PC" if FALSE... is this as expected?
- If ARUonly is FALSE and useGRTS is FALSE, [there is no sampling](https://github.com/dhope/BASSr/blob/e4b02da4410d0f1887edc4413eb6fd8023e85202/R/SSU_selection_methods.R#L162-L177)... is this as expected?

**Comment by dhope** [comment]
Really nice work. I think I should have left the `ShortestPath` method out for you as looking at it now, I realize how 'hacky' my solution was. However, I think it could be a useful function for us in the future, so I appreciate your work on it.

> ### But still some questions...

> **Shortest path** In the examples I have, the spacing among sites is 300m, but the `min_dist` used in the functions is also 300m. So I have a couple of questions about how to replace the hard-coded options with more flexible variables

> * The [buffer distance](https://github.com/dhope/BASSr/blob/e4b02da4410d0f1887edc4413eb6fd8023e85202/R/SSU_selection_methods.R#L197-L198) around the sites is `20 + sqrt(2 * (300**2))`.
>   
>   * To allow this to be flexible, should this be `20 + sqrt(2 * (spacing**2))`? Or should I use `min_dist`?

I think we want a `spacing` variable as you describe. The `min_dist` is for distance between selected points, which may be different than the spacing of the points we are selecting from. In our case this is for ARUs, our site population spacing is 300m, but we decided having sites closer than 600m would be wasted effort and likely record the same birds, causing issues with closure.

> * The [weighted distance between points](https://github.com/dhope/BASSr/blob/e4b02da4410d0f1887edc4413eb6fd8023e85202/R/SSU_selection_methods.R#L208) in a path is hard-coded as 150 being too close, min_dist + 5 good, and everything else intermediate (if I've understood).
>   
>   * Should 150 be replace with `spacing/2` ?

Yes, I think that is reasonable.

> 
> **Non-GRTS Sampling**
> 
> * The functions use (or create) the `scaled_benefit` column, but [sometimes use the `benefit` column to sort the data](https://github.com/dhope/BASSr/blob/e4b02da4410d0f1887edc4413eb6fd8023e85202/R/SSU_selection_methods.R#L45)... is this as expected, or should they be sorting by `scaled_benefit`?

I don't think it should matter as both `scaled_benefit` and `benefit` should be equivalently ordered. However, for consistency, yeah should sort on what we are selecting on so can switch to `scaled_benefit`.

> * Non-GRTS doesn't seem to use `min_dist`, so there is no check for the distance between sampled sites... is this as expected?

This is probably an oversight when I was writing the function. If easy to add, that'd be great, otherwise can just file another issue for later.

> * Non-GRTS Clusters only accept samples if at least two points are with 675m of each other [ie. the minimum distance among points is < 675m](https://github.com/dhope/BASSr/blob/e4b02da4410d0f1887edc4413eb6fd8023e85202/R/SSU_selection_methods.R#L38-L50), is this as expected?

This is essentially set up to avoid clusters overlapping with each other. The 675 should probably be standardized based on spacing of site population.  I think I used `sqrt(300**2+150**2)*2` as my points are essentially triangles from each other, so could use that with spacing replacing `300`, but I should probably double check that. 

We wouldn't want a situation where spacing is 1000m and then the function won't run or runs incorrectly, so yeah that is a danger. Good catch.


> **Random Sampling**
> 
> * For ARUonly, all points are labelled "ARU" if TRUE and "PC" if FALSE... is this as expected?

I don't think I set it up to have mixed modes for random sampling yet. Essentially point counts are generally done in clusters, whereas ARUs are more dispersed. Likely another issue for me to deal with later (#11)

> * If ARUonly is FALSE and useGRTS is FALSE, [there is no sampling](https://github.com/dhope/BASSr/blob/e4b02da4410d0f1887edc4413eb6fd8023e85202/R/SSU_selection_methods.R#L162-L177)... is this as expected?

Again, it is unlikely that a situation would arise where you'd do point counts without a cluster, but for the code, yeah this is wrong and should be fixed. I've added to #11 in case you don't get to it.
